// <auto-generated />
namespace Sportingclub1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class d31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d31));
        
        string IMigrationMetadata.Id
        {
            get { return "202010051626179_d31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
